services:
  api:
    build:
      context: .
      dockerfile: ObiletDemo.API/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - obilet-network

  web:
    build:
      context: .
      dockerfile: ObiletDemo.Web/Dockerfile
    ports:
      - "5002:80"
      - "5003:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api
    networks:
      - obilet-network

networks:
  obilet-network:
    driver: bridge 