services:
  api:
    build:
      context: .
      dockerfile: ObiletDemo.API/Dockerfile
    ports:
      - "5007:5007"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - obilet-network

  web:
    build:
      context: .
      dockerfile: ObiletDemo.Web/Dockerfile
    ports:
      - "5006:5006"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api
    networks:
      - obilet-network

networks:
  obilet-network:
    driver: bridge 